<a href="https://colab.research.google.com/github/Teixeiras15-collab/Atividades/blob/main/Numpay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Nível 1: Básico — Faturamento Semanal e Filtros**

In [2]:
import numpy as np

**#### Passo 1: Crie um array unidimensional chamado `pecas_vendidas` contendo o histórico diário da semana: `[150, 120, 90, 210, 300, 250, 180]` utilizando a função `np.array()`.**

In [3]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])
display(pecas_vendidas)

array([150, 120,  90, 210, 300, 250, 180])

**#### Passo 2: A gerência pediu uma estimativa rápida de faturamento. Sabendo que o preço médio de cada peça é de R$ 50,00, crie um novo array multiplicando o array original por 50. Observe como o NumPy aplica essa operação matemática a todos os elementos de uma só vez, sem a necessidade de escrever laços de repetição (operações vetorizadas).**

In [4]:
preco_peca = 50
faturamento_semanal = pecas_vendidas * preco_peca
display(faturamento_semanal)

array([ 7500,  6000,  4500, 10500, 15000, 12500,  9000])

**#### Passo 3: Identifique os dias de pico. Crie uma máscara booleana para filtrar e extrair apenas os dias em que a loja vendeu estritamente mais de 200 peças (ex: `pecas_vendidas > 200`).**

In [12]:
dias_pico_mask = pecas_vendidas > 200
display(dias_pico_mask)
dias_pico_vendas = pecas_vendidas[dias_pico_mask]
display(dias_pico_vendas)

array([False, False, False,  True,  True,  True, False])

array([210, 300, 250])

# **### Nível 2: Intermediário — Múltiplas Filiais e Falhas de Sistema**

**#### Passo 1: Crie uma matriz 2D a partir das seguintes listas para representar as vendas:**
Loja A: `[200, 220, np.nan, 250]` (Houve uma falha no sistema no 3º dia, gerando um valor não-número).
Loja B: `[150, 180, 160, 190]`
Loja C: `[300, 310, 290, 330]`

In [8]:
vendas_filiais = np.array([
    [200, 220, np.nan, 250],  # Loja A
    [150, 180, 160, 190],   # Loja B
    [300, 310, 290, 330]    # Loja C
])
display(vendas_filiais)

array([[200., 220.,  nan, 250.],
       [150., 180., 160., 190.],
       [300., 310., 290., 330.]])

**#### Passo 2: Calcule o total de peças vendidas por cada loja (agregando pelas linhas). Para isso, aplique a função de soma especificando o parâmetro `axis=1`.**

In [9]:
total_vendas_por_loja = np.nansum(vendas_filiais, axis=1) # Usando nansum para ignorar NaN
display(total_vendas_por_loja)

array([ 670.,  680., 1230.])

**#### Passo 3: A diretoria quer saber a média diária geral da rede. Como os dados reais frequentemente possuem lacunas, calcule a média utilizando a função do NumPy que ignora os valores `nan`. Se você usar a média normal, o resultado será contaminado e invalidará o relatório.**

In [10]:
media_diaria_geral = np.nanmean(vendas_filiais)
display(f"Média diária geral da rede (ignorando NaN): {media_diaria_geral:.2f}")

'Média diária geral da rede (ignorando NaN): 234.55'

**###### Passo 4: A meta diária de cada loja é vender 200 peças. Utilize a função `np.where()` para criar uma nova matriz condicional, onde os valores maiores ou iguais a 200 sejam substituídos pelo texto 'Meta Atingida', e os valores inferiores sejam substituídos por 'Abaixo'.**

In [11]:
matriz_metas = np.where(vendas_filiais >= 200, 'Meta Atingida', 'Abaixo')
display(matriz_metas)

array([['Meta Atingida', 'Meta Atingida', 'Abaixo', 'Meta Atingida'],
       ['Abaixo', 'Abaixo', 'Abaixo', 'Abaixo'],
       ['Meta Atingida', 'Meta Atingida', 'Meta Atingida',
        'Meta Atingida']], dtype='<U13')

# **### Nível 3: Avançado — Categorização e Destaques de Marketing**

**#### Passo 1: Para simular uma base de clientes, utilize o gerador moderno com uma semente fixa (`np.random.default_rng()`) para que os resultados sejam reproduzíveis. Crie uma amostra com 50 vendas sorteadas entre as opções `['Eletrônicos', 'Roupas', 'Casa']`.**

In [13]:
rng = np.random.default_rng(42) # Semente fixa para reprodutibilidade
categorias_venda = rng.choice(['Eletrônicos', 'Roupas', 'Casa'], size=50)
display(categorias_venda)

array(['Eletrônicos', 'Casa', 'Roupas', 'Roupas', 'Roupas', 'Casa',
       'Eletrônicos', 'Casa', 'Eletrônicos', 'Eletrônicos', 'Roupas',
       'Casa', 'Casa', 'Casa', 'Casa', 'Casa', 'Roupas', 'Eletrônicos',
       'Casa', 'Roupas', 'Roupas', 'Roupas', 'Eletrônicos', 'Casa',
       'Casa', 'Roupas', 'Roupas', 'Casa', 'Roupas', 'Roupas', 'Roupas',
       'Eletrônicos', 'Eletrônicos', 'Roupas', 'Casa', 'Eletrônicos',
       'Casa', 'Casa', 'Eletrônicos', 'Roupas', 'Eletrônicos', 'Casa',
       'Casa', 'Roupas', 'Eletrônicos', 'Casa', 'Roupas', 'Casa', 'Casa',
       'Casa'], dtype='<U11')

**#### Passo 2: Determine o volume de vendas de cada departamento. Utilize a função `np.unique` habilitando o argumento `return_counts=True` para obter os valores únicos e suas respectivas contagens — esta é uma forma rápida de fazer o equivalente numérico de contagem de categorias.**

In [14]:
departamentos_unicos, contagem_departamentos = np.unique(categorias_venda, return_counts=True)
display(f"Departamentos: {departamentos_unicos}")
display(f"Volume de vendas por departamento: {contagem_departamentos}")

"Departamentos: ['Casa' 'Eletrônicos' 'Roupas']"

'Volume de vendas por departamento: [21 12 17]'

**#### Passo 3: O time de marketing enviou um array com o faturamento de cinco campanhas simultâneas: `[12000, 45000, 23000, 89000, 31000]`. Identifique rapidamente a campanha campeã utilizando o método que retorna o índice (posição) do maior valor do array.**

In [16]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])
indice_campea = np.argmax(faturamento_campanhas)
display(f"O índice da campanha campeã é: {indice_campea}")
display(f"Faturamento da campanha campeã: R$ {faturamento_campanhas[indice_campea]:.2f}")

'O índice da campanha campeã é: 3'

'Faturamento da campanha campeã: R$ 89000.00'